name: release
on:
  push:
    tags:
      - "*"
env:
  GO_VERSION: "1.23"
jobs:
  publish:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make release-notes release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          allowUpdates: true
          artifacts: _output/releases/*
          bodyFile: release-notes.md
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: release-notes
          path: release-notes.md
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: build-artifacts
          path: _output
