name: release
on:
  push:
    tags:
      - "*"
env:
  GO_VERSION: "1.23"
jobs:
  publish:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make release-notes release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          allowUpdates: true
          artifacts: _output/releases/*
          bodyFile: release-notes.md
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: release-notes
          path: release-notes.md
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: build-artifacts
          path: _output
